### PR TITLE
Updating access request process for VSP

### PR DESCRIPTION
**Pull request by b00klegger**
Updating the document to account for a new issue template and repo.
Also updated locations on the Internal Tools document.

### CODE REVIEW

**Comment by ricetj** [comment]
LGTM 👍

**Comment by b00klegger** [comment]
@ricetj Do you have write access? Darn it I cannot write to the repo!
@wyattwalter Can you write to the repo?

**Comment by b00klegger** [comment]
@ricetj I opened a companion PR over there for that template this morning 🙂

**Comment by ricetj** [comment]
> @ricetj Do you have write access? Darn it I cannot write to the repo!
> @wyattwalter Can you write to the repo?
@b00klegger I do not 😞

**Comment by ricetj** [comment]
> > @ricetj Do you have write access? Darn it I cannot write to the repo!
> > @wyattwalter Can you write to the repo?
> 
> @b00klegger I do not 😞

Nancy is going to give us all access. 🎉

**Comment by gunsch** [comment]
Looks good! Do we also want to add directions for other tool access here? (Sentry, Grafana, Jenkins, etc.)

**Comment by b00klegger** [comment]
@gunsch 
would a parenthetical work better here? When we say 'developer tools' I suppose we mean Grafana, Sentry etc. Perhaps something like:
```
#### 2. Request that your SSH keys be authorized so that you can use the developer tools such as Grafana, Sentry, Jenkins.
```
the actual access to the tool is controlled  (will be controlled for Sentry) by GitHub OAuth integrations.

**Comment by gunsch** [comment]
That addition would be nice. How soon is the Sentry / GitHub OAuth integration expected? If it's more than a sprint out, we should probably add directions about that here (i.e. asking for an invite in Slack)

**Pull request merged**
