### PR TITLE
Fleshing out more Jenkins Sentry Grafana details

### PR DESCRIPTION
**Pull request by b00klegger**
This adds details for external teams in regards to internal developer tools.

### CODE REVIEW

**Comment by b00klegger** [comment]
@ricetj 
I have just updated (again!). Removed AWS console from `tools` document and instead focus on actual 'tools'. New AWS console doc for that focus -- I tried to rewrite tools to include AWS but could not make it succinct without adding more and more. 

Tools should include what was discussed yesterday.

**Comment by ricetj** [comment]
> @ricetj
> I have just updated (again!). Removed AWS console from `tools` document and instead focus on actual 'tools'. New AWS console doc for that focus -- I tried to rewrite tools to include AWS but could not make it succinct without adding more and more.
> 
> Tools should include what was discussed yesterday.

Thanks for all of this, hopefully, this will save us some time going forward. If there is no way to combine them then no worries at all. I don't want you to have to write a novel.

**Comment by b00klegger** [comment]
> I think the AWS page is the right move. How will the user get to the AWS page? Is the idea to link to that section from the "Additional onboarding steps for developers section?

Oh yeah, how about adding to the `README`? Perhaps a 
```
Step 4: Request access to AWS
- Request access to the AWS console for troubleshooting, support and deployment
```

**Comment by ricetj** [comment]
> > I think the AWS page is the right move. How will the user get to the AWS page? Is the idea to link to that section from the "Additional onboarding steps for developers section?
> 
> Oh yeah, how about adding to the `README`? Perhaps a
> 
> ```
> Step 4: Request access to AWS
> - Request access to the AWS console for troubleshooting, support and deployment
> ```

hmmm, well if they go to step 2 and create an issue they will already be prompted for AWS access in the template. Not sure the best way to do this.

**Comment by b00klegger** [comment]
@ricetj 
Take a look at this update: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/dfd230d0d827fe6107a7261aacfda5e376e244b7/Onboarding/request-access-to-tools.md

**Comment by ricetj** [comment]
> https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/dfd230d0d827fe6107a7261aacfda5e376e244b7/Onboarding/request-access-to-tools.md

This looks Great! thank you. clear for 🚀

**Pull request merged**
